### ISSUE TITLE
read_only_tables plugin option

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-sqlite-authorizer#2]
Refs:
- https://github.com/datasette/datasette-sqlite-authorizer/issues/1#issuecomment-1854956547

**Comment by simonw** [comment]
Design of this feature:

```yaml
plugins:
  datasette-sqlite-authorizer:
    read_only_tables:
    - database: content
      table: repos
```
Or leave `database` out for ALL tables with that name across all databases - useful for `_litestream_lock` and `_litestream_seq`.

```yaml
plugins:
  datasette-sqlite-authorizer:
    read_only_tables:
    - table: _litestream_lock
    - table: _litestream_seq
```
